name: 'Terraform Deploy to AWS ECR'

on: [push]
defaults:
      run:
        shell: bash
permissions:
    id-token: write   # This is required for requesting the JWT
    contents: read
jobs:
  Deploy-validate:
    name: 'Deploy Stack to AWS'
    runs-on: ubuntu-20.04
      
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2

      - name: 'Terraform Setup'
        uses: hashicorp/setup-terraform@v1

      - name: 'configure aws credentials'
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::126573314307:role/GitHubActionsRole-fbpdkpsj
          role-session-name: samplerolesession
          aws-region: 'us-west-2'

      - name: 'Terraform init and Terraform apply'
        run: | 
          aws sts get-caller-identity
          terraform init 
          terraform apply -auto-approve 
